FROM microsoft/dotnet:1.0.0-preview1

WORKDIR /app

COPY . /app/src

RUN dotnet restore -v minimal  src/
RUN dotnet publish -c release -o ./ src/
RUN rm -rf src/ $HOME/.nuget/

ENTRYPOINT dotnet Worker.dll